Change release documentation and small fix to switcher script
DeiC-HPC/cotainr pull request #38
Opened 2023-05-17 07:43 UTC by rloewe

When reviewing this, you should also check the whole `create_switcher.py` script. The commit is not part of this pull request.

2023-05-22 11:01 UTC, Chroxvi requested changes
Generally this looks very good. I have a few suggested changes as well as some bullets for discussion.

First of all, as part of this PR, we should also update https://cotainr.readthedocs.io/en/latest/development/test_suite_ci_cd.html#read-the-docs-continuous-documentation to mention the new RTD automation rule ("CalVer releases") that automatically activates all git tagged versions on RTD.

A few other things we might consider to implement in this PR as well (or in relation to):
- Switch the default version on RTD to "stable".
- Update the release notes (https://cotainr.readthedocs.io/en/latest/release_notes/index.html) to include a linked to the specific version of the docs on RTD, e.g the headline "2023.02.0" could be a link to https://cotainr.readthedocs.io/en/2023.02.0/. If make this change, the `release_note.md.template` should be updated accordingly.
- Changing the version number being shown on the https://cotainr.readthedocs.io/en/latest/index.html to something along the lines of "Unreleased development version (<git_hash>)", i.e. changing the `version` variable in `doc/conf.py` when on  RTD and building the "latest" version. This should be possible by exploiting the RTD environment variables (https://docs.readthedocs.io/en/stable/reference/environment-variables.html)
- Adding a (somewhat unrelated) note to the release guide about updating the `README.md` Easybuild easyconfig example to use the new version of cotainr.

2023-06-29 11:19 UTC, rloewe commented on doc/create_switcher.py
> +for tag in tags[0:3]:
It is in the releasing.rst guide. But would you also want a comment in the code?

2023-06-30 05:30 UTC, Chroxvi commented on doc/create_switcher.py
> +for tag in tags[0:3]:
Yes, please - possibly with a reference to the documentation

2023-07-04 11:48 UTC, rloewe commented
I have fixed the issued mentioned in the code. I have also:

- Changed the default documentation to stable
- Added links to release specific documentation in release notes and templates
- Added a note about update README.md EasyBuild script in releasing documentation

I have not done anything about the latest tag. I felt that would be too time-consuming to fix in a good way.

2023-07-05 06:41 UTC, Chroxvi approved these changes
Excellent! I think this is ready to be merged.

Let's leave any changes to the handling of the "latest" tag for another PR.

2023-07-05 06:41 UTC, merged