Set up standard Python packaging
DeiC-HPC/cotainr pull request #57
Opened 2024-07-25 07:47 UTC by akx

This PR sets up modern standard Python packaging using [Hatch](https://hatch.pypa.io/)'s Hatchling build backend.

Major changes are:

* the introduction of a standard `pyproject.toml` file
* `cotainr` now has [a standard console script entrypoint](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#console-scripts), so `bin/cotainr` is no longer technically needed 
* extra requirements (`test`, `docs`) are now specified in the `pyproject.toml` file (so installable via `pip install -e .[test,docs]`)

This makes Cotainr installable and available directly via e.g.

```
pip install git+https://github.com/DeiC-HPC/cotainr.git
```
(or a built wheel – there's a GHA workflow for that too).

Please see https://github.com/akx/cotainr/pull/1 for CI results in my fork.

2024-07-30 12:15 UTC, eskech commented
Just a short comment. @Chroxvi  is on vacation and is back in two weeks. I really want him to do the review. Sorry for letting you wait until he is back.

2024-08-26 09:31 UTC, akx commented
Gentle nudge (as I too am back from vacation) :)

2024-08-27 04:37 UTC, Chroxvi commented
@akx Thanks a lot for this contribution - and sorry for not getting back to you any sooner.

I definitely agree that we need a proper modern packaging setup for cotainr. Actually, I was working on something very similar in https://github.com/DeiC-HPC/cotainr/compare/main...pip_package, but got distracted by other tasks before I managed to finish it up. My goal was to not only have a proper packaging setup, but also to have an automatic pipeline for building wheels and publishing them on PyPi. I am happy, though, to start with just merging a proper packaging setup, and then revisiting the PyPi publishing in another PR.

Since you work in this PR is almost identical to what I was trying out in https://github.com/DeiC-HPC/cotainr/compare/main...pip_package, we need to consolidate those two branches into a single approach to this. I don't have much experience with all the different available Python packaging tools, nor any strong opinion about specific tools to use. I chose to base my work on "flit" since it seems to be the simplest way to build pure Python packages. Would you recommend "hatchling" and "build" over "flit"? If so, why? Also do you have any other valuable insights that we should consider when implementing this Python packing setup?

2024-08-27 05:55 UTC, akx commented
> [...] but got distracted by other tasks before I managed to finish it up.

Story of my life! 😂 

> My goal was to not only have a proper packaging setup, but also to have an automatic pipeline for building wheels and publishing them on PyPi. I am happy, though, to start with just merging a proper packaging setup, and then revisiting the PyPi publishing in another PR.

You'll be glad to hear that PyPI publishing is practically trivial to add on top of this; a [CI step like this]( https://github.com/valohai/oidckit/blob/d1e2421947955eaf642f8c3998e0e96502683dbc/.github/workflows/ci.yml#L50-L70) would automagically publish to PyPI when a tag is pushed.

> I chose to base my work on "flit" since it seems to be the simplest way to build pure Python packages. Would you recommend "hatchling" and "build" over "flit"? If so, why? 

[`build`](https://build.pypa.io/en/stable/) is the canonical, standard, correct Python build frontend. It's orthogonal (or well, on a different layer) c.f. Flit or Hatch. (You can actually use it with Flit-based packages too, since `flit_core` is a PEP517 build _backend_.)

I prefer [Hatch](https://hatch.pypa.io/latest/) (its build backend being `hatchling`, like `flit` contains extras over `flit_core`) because I'm very familiar with it, it has sane defaults, the developers are friendly and responsive on GitHub, it's being maintained, etc.

> Also do you have any other valuable insights that we should consider when implementing this Python packing setup?

Well, for one, I would heavily consider getting rid of the explicit `bin/cotainr` wrapper (touching `sys.path` is 99% of the time a bad move), since a well-behaved wrapper will be provided by the installed package anyway. I didn't want to do that here, though, since it could be a breaking change for some users.

2025-02-07 10:42 UTC, akx commented
@Chroxvi @joasode Rebased.

2025-02-07 11:43 UTC, joasode requested changes
Thanks a lot for continually rebasing and keeping the branch up-to-date! I have a few requested changes based on decisions we have recently made.

2025-02-07 11:43 UTC, joasode commented on pyproject.toml
I think having dynamic versioning is a good idea. However, we have decided to use Setuptools as the build back-end since we do not want to add unnecessary complexity and tools to the project. See #93. Dynamic versioning with setuptools can be done as shown here https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata

Note, I attempted to build the docs (with uv pip) and it failed in this commit with hatch backend, but succeed with Setuptools, which tells me this is the correct choice:
```
(cotainr) joaso@joaso-laptop:~/Documents/work-projects/quick-tasks/cotainr$ uv pip install -e .[docs]
  × Failed to build `cotainr @ file:///home/joaso/Documents/work-projects/quick-tasks/cotainr`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `hatchling.build.prepare_metadata_for_build_editable` failed (exit status: 1)
```

2025-02-07 11:43 UTC, joasode commented on docs-requirements.txt
We would like to keep the deprecated requirements file around for a bit, see #90

2025-02-07 11:43 UTC, joasode commented on test-requirements.txt
We would like to keep the deprecated requirements file around for a bit, see #90

2025-02-07 11:43 UTC, joasode commented on doc/development/cli_internals.rst
Similar to my comment on `bin/cotainr/` 

```suggestion
- The main way to invoke the CLI (sub)commands is via the `bin/cotainr` script, e.g.
+ The main way to invoke the CLI (sub)commands in an HPC environment is via the `bin/cotainr` script, e.g.
```
Then we can add the following suggestion for installed environments
```suggestion
+ Additionally, the CLI (sub)commands can be invoked via the `cotainr` entrypoint that is installed when installing the package, e.g.
+
+.. code-block:: console
+
+    $ cotainr build <positional_arg> <non-positional args>
+    $ cotainr info
```

2025-02-07 11:43 UTC, joasode commented on bin/cotainr
I think this comment is unnecessary, cotainr is largely made for HPC environments, where building the package via `pip install` often introduce additional inconvenience. We don't want to encourage users or developers to having to use virtual environments to use cotainr. This is the primary reason why one of the core tenants of `cotainr` is currently that we want no required dependencies beside stock Python.

2025-02-07 11:43 UTC, joasode commented on .github/workflows/CI_pull_request.yml
> +      - run: python -m build .
This should use `uv` as build frontend, https://docs.astral.sh/uv/guides/integration/github/.

2025-02-07 11:53 UTC, akx commented on pyproject.toml
@joasode Erm. "[...] but succeed with Setuptools, which tells me this is the correct choice" is a bit bold of you to say, since if you look at the actual error that hatch outputs (that was elided above),

> ValueError: Unknown classifier in field `project.classifiers`: Development Status :: 5 - Stable

it's Hatch complaining about an invalid classifier that you added in c2e37a7f033bbe470c9cdf5aae538a37765848d8. IOW, `hatch` is being **more** correct, validating the pyproject.toml file unlike the setuptools backend.

2025-02-07 12:07 UTC, akx commented on bin/cotainr
I'm not following – what is additional inconvenience? 

* `pip install` does not build packages if they're already wheels (as is likely the distribution plan) – it just basically unpacks a `.whl` (which is a ZIP) into place.
* With `uv` (which is trivially "installed" by just untarring the binary somewhere, if one doesn't want to use their convenience installer script), one doesn't need to think about virtualenvs or installation; `uvx cotainr ...` and you're off to the races.

2025-02-07 12:11 UTC, joasode commented on pyproject.toml
Thank you for noticing this. However, we are waiting on this issue https://github.com/astral-sh/uv/issues/3957, to possibly introduce a uv build backend, and have decided to use Setuptools until then to avoid unnecessary "tool-hopping".

2025-02-07 12:35 UTC, joasode commented on pyproject.toml
What is the type of workflow you're using where you think hatchling build backend makes a difference from the setuptools build backend for our project? Is it mainly for pyproject.toml validation and the [tool.hatch.version] table?

2025-02-08 16:23 UTC, akx commented on bin/cotainr
That's not exclusive to this branch. That's what'd happen on the `main` branch too, if the `~/.local/bin` directory (or wherever your package installer, be it pip, uv, conda, or whatever) decides to put the generated entrypoint script.

The `./bin/cotainr` script is worse than the generated entrypoint script in that it requires to live exactly next to the checkout (and hacks `sys.path` to deal with that). That wouldn't ever be the case with a wheel (IOW, the `bin/cotainr` script is strictly unnecessary and incompatible with a version of Cotainr installed from a built package).

2025-02-08 16:26 UTC, akx commented on pyproject.toml
[The Hatchling "Why" page answers that better than I can.](https://hatch.pypa.io/1.13/why/#build-backend)

But in my opinion, Hatch/Hatchling has been more "Just Works" than Setuptools has, and I'm saying this as a person who has actually contributed code to Setuptools...

2025-02-10 10:19 UTC, joasode commented on bin/cotainr
Yes, I understand this is clearly correct for wheels. However, comments in the source code is strictly aimed at developers, and I expect developers should want to `git clone` the repository to run tests and build documentation, and not install the wheels. Therefore, I think this comment should be removed from this PR. 

My initial comment refer to the situation where if a developer has multiple versions of `cotainr` simultaneously on an HPC cluster. If you `pip install -e` to get the 'correct' entry-point for the different versions you would get an unknown version in your .local folder. Then the solution is to increase separation by using venvs. I realize many prefers this workflow (myself included), and it is the standard python way. However we discourage this on LUMI, because with many users on the system, they (the venvs) tend to create too many small files for the Lustre parallel file system.

2025-02-10 10:36 UTC, akx commented on bin/cotainr
> I expect developers should want to git clone the repository to run tests and build documentation, and not install the wheels.

The standard procedure for developers is to install a repo as editable (eg. `pip install -e .[dev]`) which brings the entrypoint into the venv, hence no need for this script. A developer may also execute `python -m cotainr` from their working copy directory (even without having installed as editable) to the same effect as this script, but in a more standard/canonical Python way. 

If it was up to me, I'd remove this script altogether to avoid TMTOWDI. 

> However we discourage this on LUMI, because with many users on the system, they (the venvs) tend to create too many small files for the Lustre parallel file system.

I still find it so very silly that the fastest computer on the continent is hobbled by virtualenvs, but that's beside the point...

If you want to distribute Cotainr in as little files as possible (one file, to be particular), see the [zipapp standard library module](https://docs.python.org/3/library/zipapp.html). This is well supported wherever a Python is installed - we use a zipapp executable at @valohai to have VMs bootstrap themselves.

2025-02-18 09:07 UTC, joasode commented on pyproject.toml
Thanks, I have read this and find that the feature of default reproducible builds is an attractive feature of Hatchling for cotainr. We have discussed this agreed to use hatchling as build backend for now.

2025-02-18 09:18 UTC, joasode approved these changes
Thank you, This looks good, though it might need a quick re-basing due to #113.

2025-02-18 09:32 UTC, akx commented
@joasode Rebased. 👍

2025-02-18 09:53 UTC, merged