Follow-up on CI & lint stuff
DeiC-HPC/cotainr pull request #65
Opened 2024-09-11 06:15 UTC by akx

The promised follow-up to #56 (one of them, anyway).

This enables some of the rule categories discussed in https://github.com/DeiC-HPC/cotainr/pull/56#discussion_r1746722406.

E.g. selecting `S` (bandit, i.e. security) flags practically all uses of `subprocess.run`, which there are many, so that's elided from here.

2024-09-11 06:42 UTC, akx commented
The single test failure is unrelated:

```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/conda-forge/noarch'
```

2024-11-15 12:06 UTC, akx commented
Rebased once again. cc @Chroxvi @joasode – this should be pretty simple to review & merge (maybe unlike my other pending PRs are)

2025-02-07 10:37 UTC, akx commented
@Chroxvi @joasode rebased.

2025-03-04 13:02 UTC, akx commented
@Chroxvi @joasode Rebased.

2025-03-05 13:23 UTC, Chroxvi requested changes
@akx I think this is great! I have added a couple of comments, I would like your view on.

2025-03-05 16:07 UTC, akx commented on cotainr/__init__.py
> -        % (
Ah, the context helps. Sure, this change can be reverted & ignored from further changes.

2025-03-05 16:11 UTC, akx commented on cotainr/cli.py
> -from abc import ABC, abstractmethod
Sure – if the "house style" in this project is sort-within-sections, then let's enable that.

2025-03-06 06:38 UTC, Chroxvi approved these changes
I'll merge this now. @akx thanks a lot for this contribution!

2025-03-06 06:38 UTC, merged